name: Build all sheets
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Enable proposed source
        run: |
          cat <<EOF >/etc/apt/sources.list.d/ubuntu-$(lsb_release -cs)-proposed.list
          # Enable Ubuntu proposed archive
          deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-proposed restricted main multiverse universe
          EOF

      - name: Install Lilypond
        run: sudo apt-get install -y lilypond
      - name: Download font
        run: "mkdir -pv ~/.fonts && wget -P ~/.fonts/ https://github.com/adobe-fonts/source-han-serif/releases/download/2.001R/01_SourceHanSerif.ttc.zip"
      - name: Extract font
        run: "pushd ~/.fonts && unzip 01_SourceHanSerif.ttc.zip && popd"

      - uses: actions/checkout@v3
      - name: Build sheets
        run: "bash make-all.sh"
